# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clamping <- function(img) {
    .Call(`_Kaleido_clamping`, img)
}

im_height <- function(img) {
    .Call(`_Kaleido_im_height`, img)
}

im_width <- function(img) {
    .Call(`_Kaleido_im_width`, img)
}

im_nc <- function(img) {
    .Call(`_Kaleido_im_nc`, img)
}

im_npix <- function(img) {
    .Call(`_Kaleido_im_npix`, img)
}

im_rep <- function(img) {
    .Call(`_Kaleido_im_rep`, img)
}

feather <- function(img) {
    .Call(`_Kaleido_feather`, img)
}

nostalgia <- function(img) {
    .Call(`_Kaleido_nostalgia`, img)
}

lighting <- function(img, centerx = 0.5, centery = 0.5, strength = 0.5) {
    .Call(`_Kaleido_lighting`, img, centerx, centery, strength)
}

fleetingtime <- function(img) {
    .Call(`_Kaleido_fleetingtime`, img)
}

sketcher <- function(img, ksize = 15L, cont = 5L, sigma = 50) {
    .Call(`_Kaleido_sketcher`, img, ksize, cont, sigma)
}

